### ISSUE TITLE
Migration path issue

### ISSUE THREAD

**Issue by VarunAnandK** [AlvaroIsrael/zombie-survival-social-network#13]
While running : npm run knex:migrate

Output :
npx knex migrate:latest --knexfile src/config/knexfile.ts
Requiring external module ts-node/register
Working directory changed to ~/xxxxx/zombie-survival-social-network/src/config
Error: ENOENT: no such file or directory, scandir xxxx/zombie-survival-social-network/src/config/src/database/migrations

**Comment by AlvaroIsrael** [comment]
@VarunAnandK fixed by d1cacb90c522747ac9f713c04e765ba357b8aceb.
This project is still in it's very early stages! (You may find a lot of silly mistakes like this one).
